# Generated by Django 5.1 on 2024-08-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazar", "0002_item_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="evento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bazar.evento",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="evento_fim",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="evento_inicio",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
