# Generated by Django 4.2.11 on 2024-09-18 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bazar", "0004_alter_item_preco"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="nome_usuario",
            new_name="nome",
        ),
        migrations.AddField(
            model_name="usuario",
            name="usuario",
            field=models.OneToOneField(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
