# Generated by Django 4.2.11 on 2024-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazar", "0005_rename_nome_usuario_usuario_nome_usuario_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="evento",
        ),
        migrations.AddField(
            model_name="item",
            name="evento",
            field=models.ManyToManyField(null=True, to="bazar.evento"),
        ),
    ]
