# Generated by Django 4.2.11 on 2024-09-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bazar", "0007_remove_item_evento_item_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="evento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bazar.evento",
            ),
        ),
    ]
