# Generated by Django 4.2.11 on 2024-09-18 18:02

import bazar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazar", "0008_alter_item_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to=bazar.models.upload_image_item
            ),
        ),
    ]
