# Generated by Django 4.2.11 on 2024-09-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazar", "0009_alter_item_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
