# Generated by Django 4.2.11 on 2024-09-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bazar", "0011_reserva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="bazar.item"
            ),
        ),
    ]
