# Generated by Django 4.2.11 on 2024-09-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bazar", "0012_alter_reserva_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="quantidade",
        ),
    ]
